# The URL the site will be built for
base_url = "https://mingablick.de"
title = "Mingablick"
generate_feeds = true
default_language = "de"
theme = "boring"
minify_html = true
feed_filenames = ["rss.xml"]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
homepage_title = "Mingablick"
homepage_subtitle = "Mei Blick auf Minga und die Welt"
homepage_img_url = "image-dark.jpg"
google_analytics_measurement_id = "123"